import { empleadoService, politicaService } from "@model";

const crearEmpleados = async () => {
  // Datos de ejemplo para empleados
  const empleados = [
    {
      tipo_empleado: "docentes",
      nombres: "Docente1",
      apellidos: "Apellido1",
      ci: 1234561,
      fecha_nacimiento: "1980-01-01",
      telefono: "1234567890",
      correo_electronico: "docente1@demo.com",
      fecha_ingreso_mppe: "2010-01-01",
      direccion_de_habitacion: "Direccion 1",
      codigo_cargo: "C001",
      dependencia_nominal: "Dependencia 1",
      estatus: true,
      reposo_permiso: "Ninguno",
      anos_servicio: 10,
      observaciones: "Ninguna",
      titulo_pregrado: "Licenciado en Educación",
      area_docente_especialista: "Matemáticas",
      grado_seccion: "Primaria",
      funcion_trabajo: "Docente",
      acarigua: "",
      titulo_obtenido: "",
    },
    {
      tipo_empleado: "docentes",
      nombres: "Docente2",
      apellidos: "Apellido2",
      ci: 1234562,
      fecha_nacimiento: "1981-01-01",
      telefono: "1234567891",
      correo_electronico: "docente2@demo.com",
      fecha_ingreso_mppe: "2011-01-01",
      direccion_de_habitacion: "Direccion 2",
      codigo_cargo: "C002",
      dependencia_nominal: "Dependencia 2",
      estatus: true,
      reposo_permiso: "Ninguno",
      anos_servicio: 9,
      observaciones: "Ninguna",
      titulo_pregrado: "Licenciado en Educación",
      area_docente_especialista: "Ciencias",
      grado_seccion: "Secundaria",
      funcion_trabajo: "Docente",
      acarigua: "",
      titulo_obtenido: "",
    },
    {
      tipo_empleado: "docentes",
      nombres: "Docente3",
      apellidos: "Apellido3",
      ci: 1234563,
      fecha_nacimiento: "1982-01-01",
      telefono: "1234567892",
      correo_electronico: "docente3@demo.com",
      fecha_ingreso_mppe: "2012-01-01",
      direccion_de_habitacion: "Direccion 3",
      codigo_cargo: "C003",
      dependencia_nominal: "Dependencia 3",
      estatus: true,
      reposo_permiso: "Ninguno",
      anos_servicio: 8,
      observaciones: "Ninguna",
      titulo_pregrado: "Licenciado en Educación",
      area_docente_especialista: "Historia",
      grado_seccion: "Primaria",
      funcion_trabajo: "Docente",
      acarigua: "",
      titulo_obtenido: "",
    },
    {
      tipo_empleado: "docentes",
      nombres: "Docente4",
      apellidos: "Apellido4",
      ci: 1234564,
      fecha_nacimiento: "1983-01-01",
      telefono: "1234567893",
      correo_electronico: "docente4@demo.com",
      fecha_ingreso_mppe: "2013-01-01",
      direccion_de_habitacion: "Direccion 4",
      codigo_cargo: "C004",
      dependencia_nominal: "Dependencia 4",
      estatus: true,
      reposo_permiso: "Ninguno",
      anos_servicio: 7,
      observaciones: "Ninguna",
      titulo_pregrado: "Licenciado en Educación",
      area_docente_especialista: "Geografía",
      grado_seccion: "Secundaria",
      funcion_trabajo: "Docente",
      acarigua: "",
      titulo_obtenido: "",
    },
    {
      tipo_empleado: "docentes",
      nombres: "Docente5",
      apellidos: "Apellido5",
      ci: 1234565,
      fecha_nacimiento: "1984-01-01",
      telefono: "1234567894",
      correo_electronico: "docente5@demo.com",
      fecha_ingreso_mppe: "2014-01-01",
      direccion_de_habitacion: "Direccion 5",
      codigo_cargo: "C005",
      dependencia_nominal: "Dependencia 5",
      estatus: true,
      reposo_permiso: "Ninguno",
      anos_servicio: 6,
      observaciones: "Ninguna",
      titulo_pregrado: "Licenciado en Educación",
      area_docente_especialista: "Física",
      grado_seccion: "Primaria",
      funcion_trabajo: "Docente",
      acarigua: "",
      titulo_obtenido: "",
    },
    {
      tipo_empleado: "obreros",
      nombres: "Obrero1",
      apellidos: "Apellido1",
      ci: 2234561,
      fecha_nacimiento: "1985-01-01",
      telefono: "2234567890",
      correo_electronico: "obrero1@demo.com",
      fecha_ingreso_mppe: "2015-01-01",
      direccion_de_habitacion: "Direccion 6",
      codigo_cargo: "C006",
      dependencia_nominal: "Dependencia 6",
      estatus: true,
      reposo_permiso: "Ninguno",
      anos_servicio: 5,
      observaciones: "Ninguna",
      titulo_pregrado: "",
      area_docente_especialista: "",
      grado_seccion: "",
      funcion_trabajo: "",
      acarigua: "Acarigua 1",
      titulo_obtenido: "Bachiller",
    },
    {
      tipo_empleado: "obreros",
      nombres: "Obrero2",
      apellidos: "Apellido2",
      ci: 2234562,
      fecha_nacimiento: "1986-01-01",
      telefono: "2234567891",
      correo_electronico: "obrero2@demo.com",
      fecha_ingreso_mppe: "2016-01-01",
      direccion_de_habitacion: "Direccion 7",
      codigo_cargo: "C007",
      dependencia_nominal: "Dependencia 7",
      estatus: true,
      reposo_permiso: "Ninguno",
      anos_servicio: 4,
      observaciones: "Ninguna",
      titulo_pregrado: "",
      area_docente_especialista: "",
      grado_seccion: "",
      funcion_trabajo: "",
      acarigua: "Acarigua 2",
      titulo_obtenido: "Bachiller",
    },
    {
      tipo_empleado: "obreros",
      nombres: "Obrero3",
      apellidos: "Apellido3",
      ci: 2234563,
      fecha_nacimiento: "1987-01-01",
      telefono: "2234567892",
      correo_electronico: "obrero3@demo.com",
      fecha_ingreso_mppe: "2017-01-01",
      direccion_de_habitacion: "Direccion 8",
      codigo_cargo: "C008",
      dependencia_nominal: "Dependencia 8",
      estatus: true,
      reposo_permiso: "Ninguno",
      anos_servicio: 3,
      observaciones: "Ninguna",
      titulo_pregrado: "",
      area_docente_especialista: "",
      grado_seccion: "",
      funcion_trabajo: "",
      acarigua: "Acarigua 3",
      titulo_obtenido: "Bachiller",
    },
    {
      tipo_empleado: "obreros",
      nombres: "Obrero4",
      apellidos: "Apellido4",
      ci: 2234564,
      fecha_nacimiento: "1988-01-01",
      telefono: "2234567893",
      correo_electronico: "obrero4@demo.com",
      fecha_ingreso_mppe: "2018-01-01",
      direccion_de_habitacion: "Direccion 9",
      codigo_cargo: "C009",
      dependencia_nominal: "Dependencia 9",
      estatus: true,
      reposo_permiso: "Ninguno",
      anos_servicio: 2,
      observaciones: "Ninguna",
      titulo_pregrado: "",
      area_docente_especialista: "",
      grado_seccion: "",
      funcion_trabajo: "",
      acarigua: "Acarigua 4",
      titulo_obtenido: "Bachiller",
    },
    {
      tipo_empleado: "obreros",
      nombres: "Obrero5",
      apellidos: "Apellido5",
      ci: 2234565,
      fecha_nacimiento: "1989-01-01",
      telefono: "2234567894",
      correo_electronico: "obrero5@demo.com",
      fecha_ingreso_mppe: "2019-01-01",
      direccion_de_habitacion: "Direccion 10",
      codigo_cargo: "C010",
      dependencia_nominal: "Dependencia 10",
      estatus: true,
      reposo_permiso: "Ninguno",
      anos_servicio: 1,
      observaciones: "Ninguna",
      titulo_pregrado: "",
      area_docente_especialista: "",
      grado_seccion: "",
      funcion_trabajo: "",
      acarigua: "Acarigua 5",
      titulo_obtenido: "Bachiller",
    },
  ];

  // Insertar empleados en la base de datos
  for (const empleado of empleados) {
    empleadoService.createEmpleado(
      empleado.tipo_empleado,
      empleado.nombres,
      empleado.apellidos,
      empleado.ci,
      empleado.fecha_nacimiento,
      empleado.telefono,
      empleado.correo_electronico,
      empleado.fecha_ingreso_mppe,
      empleado.direccion_de_habitacion,
      empleado.codigo_cargo,
      empleado.dependencia_nominal,
      empleado.estatus,
      empleado.reposo_permiso,
      empleado.anos_servicio,
      empleado.observaciones,
      empleado.titulo_pregrado,
      empleado.area_docente_especialista,
      empleado.grado_seccion,
      empleado.funcion_trabajo,
      empleado.acarigua,
      empleado.titulo_obtenido
    );
  }

  // Datos de ejemplo para políticas
  const politica = [
    {
      id_empleado: 1,
      inscrito_psuv: true,
      pertenece_movimiento_social: "Movimiento A",
      carnet_patria_codigo: "1234567890",
      carnet_patria_serial: "A1B2C3D4",
      centro_votacion: "Centro 1",
      tipo_voto: "Tipo 1",
    },
    {
      id_empleado: 2,
      inscrito_psuv: false,
      pertenece_movimiento_social: "Movimiento B",
      carnet_patria_codigo: "0987654321",
      carnet_patria_serial: "D4C3B2A1",
      centro_votacion: "Centro 2",
      tipo_voto: "Tipo 2",
    },
    {
      id_empleado: 3,
      inscrito_psuv: true,
      pertenece_movimiento_social: "Movimiento C",
      carnet_patria_codigo: "1122334455",
      carnet_patria_serial: "E5F6G7H8",
      centro_votacion: "Centro 3",
      tipo_voto: "Tipo 3",
    },
    {
      id_empleado: 4,
      inscrito_psuv: false,
      pertenece_movimiento_social: "Movimiento D",
      carnet_patria_codigo: "5566778899",
      carnet_patria_serial: "H8G7F6E5",
      centro_votacion: "Centro 4",
      tipo_voto: "Tipo 4",
    },
    {
      id_empleado: 5,
      inscrito_psuv: true,
      pertenece_movimiento_social: "Movimiento E",
      carnet_patria_codigo: "6677889900",
      carnet_patria_serial: "I9J0K1L2",
      centro_votacion: "Centro 5",
      tipo_voto: "Tipo 5",
    },
  ];

  politica.forEach((data) => {
    politicaService.createPolitica(
      data.id_empleado,
      data.inscrito_psuv,
      data.pertenece_movimiento_social,
      data.carnet_patria_codigo,
      data.carnet_patria_serial,
      data.centro_votacion,
      data.tipo_voto
    );
  });
};

export default crearEmpleados;
